name: Flushing Gospel Hall
safe: false
baseurl: flushinggospelhall.org
url: http://flushinggospelhall.org
permalink: pretty
plugins: _plugin
markdown: redcarpet
highlighter: true
languages: ["en", "kr"]

exclude_from_localizations: [ "bower_components", 
                              "stylesheets",
                              "js",
                              "img",
                              "CNAME",
                              "favicon.ico",
                              "googlec7315de222f6e6ff.html",
                              "humans.txt",
                              "README.txt",
                              "robots.txt",
                              "sitemap.xml"]
                            
exclude: ["node_modules", 
          "scss",
          "bower.json", 
          "Gemfile", 
          "Gemfile.lock", 
          "Gruntfile.js", 
          "package.json", 
          "rakefile.rb", 
          "run.sh", 
          "test.sh",
          "README.txt"]

